In [124]:
import pandas as pd

In [125]:
# import crime data
df = pd.read_csv('./crime-2024.csv')

In [126]:
# initial look
df.head(3)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,Report Type Code,Report Type Description,Filed Online,Incident Code,Incident Category,Incident Subcategory,Incident Description,Resolution,Intersection,CNN,Police District,Analysis Neighborhood,Supervisor District,Supervisor District 2012,Latitude,Longitude,Point
0,2024/01/01 12:00:00 AM,2024/01/01,00:00,2024,Monday,2025/01/27 10:07:00 AM,145753674000,1457536,250052170,250270990.0,II,Initial,NaN,74000,Missing Person,Missing Adult,Missing Adult,Open or Active,TURK MURPHY LN \ VALLEJO ST,25354000.0,Central,Chinatown,3.0,3.0,37.798443,-122.409882,POINT (-122.40988159179688 37.79844284057617)
1,2024/01/01 12:00:00 PM,2024/01/01,12:00,2024,Monday,2024/12/17 12:01:00 PM,144811206374,1448112,240776681,243521388.0,II,Initial,NaN,6374,Larceny Theft,Larceny Theft - Other,"Theft, Other Property, >$950",Open or Active,OAKDALE AVE \ RANKIN ST,20748000.0,Bayview,Bayview Hunters Point,10.0,10.0,37.738846,-122.397812,POINT (-122.39781188964844 37.73884582519531)
2,2024/01/01 12:00:00 AM,2024/01/01,00:00,2024,Monday,2025/03/31 04:44:00 PM,147297574000,1472975,250181070,250902390.0,II,Initial,NaN,74000,Missing Person,Missing Adult,Missing Adult,Open or Active,24TH AVE \ SANTIAGO ST,23262000.0,Taraval,Sunset/Parkside,4.0,4.0,37.744682,-122.481178,POINT (-122.4811782836914 37.74468231201172)

In [127]:
# print all columns names
print(df.columns.tolist())

['Incident Datetime', 'Incident Date', 'Incident Time', 'Incident Year', 'Incident Day of Week', 'Report Datetime', 'Row ID', 'Incident ID', 'Incident Number', 'CAD Number', 'Report Type Code', 'Report Type Description', 'Filed Online', 'Incident Code', 'Incident Category', 'Incident Subcategory', 'Incident Description', 'Resolution', 'Intersection', 'CNN', 'Police District', 'Analysis Neighborhood', 'Supervisor District', 'Supervisor District 2012', 'Latitude', 'Longitude', 'Point']

In [128]:
# get shape of the dataframe
print(df.shape)

(109576, 27)

In [129]:
# drop the rows where the Latitude or Longitude is NaN
df = df.dropna(subset=['Latitude', 'Longitude'])
print(df.shape)

(103523, 27)

In [130]:
# display all columns 

pd.set_option('display.max_columns', None)

In [131]:
df.head(3)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,Report Type Code,Report Type Description,Filed Online,Incident Code,Incident Category,Incident Subcategory,Incident Description,Resolution,Intersection,CNN,Police District,Analysis Neighborhood,Supervisor District,Supervisor District 2012,Latitude,Longitude,Point
0,2024/01/01 12:00:00 AM,2024/01/01,00:00,2024,Monday,2025/01/27 10:07:00 AM,145753674000,1457536,250052170,250270990.0,II,Initial,NaN,74000,Missing Person,Missing Adult,Missing Adult,Open or Active,TURK MURPHY LN \ VALLEJO ST,25354000.0,Central,Chinatown,3.0,3.0,37.798443,-122.409882,POINT (-122.40988159179688 37.79844284057617)
1,2024/01/01 12:00:00 PM,2024/01/01,12:00,2024,Monday,2024/12/17 12:01:00 PM,144811206374,1448112,240776681,243521388.0,II,Initial,NaN,6374,Larceny Theft,Larceny Theft - Other,"Theft, Other Property, >$950",Open or Active,OAKDALE AVE \ RANKIN ST,20748000.0,Bayview,Bayview Hunters Point,10.0,10.0,37.738846,-122.397812,POINT (-122.39781188964844 37.73884582519531)
2,2024/01/01 12:00:00 AM,2024/01/01,00:00,2024,Monday,2025/03/31 04:44:00 PM,147297574000,1472975,250181070,250902390.0,II,Initial,NaN,74000,Missing Person,Missing Adult,Missing Adult,Open or Active,24TH AVE \ SANTIAGO ST,23262000.0,Taraval,Sunset/Parkside,4.0,4.0,37.744682,-122.481178,POINT (-122.4811782836914 37.74468231201172)

In [132]:
df['Report Type Description'].value_counts()

Initial                68882
Coplogic Initial       12000
Initial Supplement      9592
Vehicle Initial         8511
Vehicle Supplement      3410
Coplogic Supplement     1128
Name: Report Type Description, dtype: int64

In [133]:
# only keep Initial or Vehicle Initial

df = df[df['Report Type Description'].isin(['Initial', 'Vehicle Initial'])]

In [134]:
df['Report Type Description'].value_counts()

Initial            68882
Vehicle Initial     8511
Name: Report Type Description, dtype: int64

In [135]:
# get a list of the unique Incident Category
incident_categories = df['Incident Category'].unique()
print(incident_categories)

['Missing Person' 'Larceny Theft' 'Malicious Mischief' 'Fraud'
 'Other Miscellaneous' 'Other Offenses' 'Embezzlement'
 'Motor Vehicle Theft' 'Assault' 'Robbery' 'Drug Offense'
 'Disorderly Conduct' 'Miscellaneous Investigation' 'Burglary'
 'Non-Criminal' 'Arson' 'Other' 'Vandalism'
 'Offences Against The Family And Children' 'Warrant' 'Recovered Vehicle'
 'Lost Property' 'Forgery And Counterfeiting' 'Sex Offense'
 'Suspicious Occ' 'Weapons Offense' 'Weapons Carrying Etc' 'Fire Report'
 'Traffic Violation Arrest' 'Stolen Property' 'Suicide' 'Courtesy Report'
 'Rape' 'Vehicle Impounded' 'Drug Violation' nan 'Traffic Collision'
 'Liquor Laws' 'Prostitution' 'Motor Vehicle Theft?' 'Case Closure'
 'Suspicious' 'Gambling' 'Homicide'
 'Human Trafficking (A), Commercial Sex Acts' 'Weapons Offence'
 'Vehicle Misplaced' 'Human Trafficking (B), Involuntary Servitude'
 'Civil Sidewalks']

I only want: Assault, Burglary, Larceny, Motor vehicle theft, Robbery.

In [136]:
# define the categories to keep and consolidate
assault_cats = ['Assault']
burglary_cats = ['Burglary']
larceny_cats = ['Larceny Theft', 'Embezzlement', 'Stolen Property']
mv_theft_cats = ['Motor Vehicle Theft', 'Motor Vehicle Theft?']
robbery_cats = ['Robbery']

In [137]:
# create a list of all categories to keep
keep_categories = assault_cats + burglary_cats + larceny_cats + mv_theft_cats + robbery_cats

In [138]:
# filter your dataframe
filtered_df = df[df['Incident Category'].isin(keep_categories)].copy()

In [139]:
# create a new consolidated category column
def consolidate_category(category):
    if category in assault_cats:
        return 'Assault'
    elif category in burglary_cats:
        return 'Burglary'
    elif category in larceny_cats:
        return 'Larceny'
    elif category in mv_theft_cats:
        return 'Motor Vehicle Theft'
    elif category in robbery_cats:
        return 'Robbery'
    else:
        return category

filtered_df['Consolidated Category'] = filtered_df['Incident Category'].apply(consolidate_category)

In [140]:
# check the results
filtered_df['Consolidated Category'].value_counts()

Larceny                12886
Assault                 7269
Motor Vehicle Theft     6498
Burglary                4984
Robbery                 2061
Name: Consolidated Category, dtype: int64

In [141]:
filtered_df.head(3)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,Report Type Code,Report Type Description,Filed Online,Incident Code,Incident Category,Incident Subcategory,Incident Description,Resolution,Intersection,CNN,Police District,Analysis Neighborhood,Supervisor District,Supervisor District 2012,Latitude,Longitude,Point,Consolidated Category
1,2024/01/01 12:00:00 PM,2024/01/01,12:00,2024,Monday,2024/12/17 12:01:00 PM,144811206374,1448112,240776681,243521388.0,II,Initial,NaN,6374,Larceny Theft,Larceny Theft - Other,"Theft, Other Property, >$950",Open or Active,OAKDALE AVE \ RANKIN ST,20748000.0,Bayview,Bayview Hunters Point,10.0,10.0,37.738846,-122.397812,POINT (-122.39781188964844 37.73884582519531),Larceny
7,2024/01/01 02:48:00 AM,2024/01/01,02:48,2024,Monday,2024/01/05 05:16:00 PM,135373527090,1353735,240011186,240052385.0,II,Initial,NaN,27090,Larceny Theft,Larceny Theft - Other,"Theft, Lost Property, Petty",Open or Active,JACKSON ST \ WALL PL,25277000.0,Central,Russian Hill,3.0,3.0,37.794643,-122.417520,POINT (-122.41752007397096 37.794643190046045),Larceny
24,2024/01/01 09:30:00 AM,2024/01/01,09:30,2024,Monday,2024/02/06 03:36:00 PM,136230406114,1362304,240081167,240372139.0,II,Initial,NaN,6114,Larceny Theft,Larceny Theft - Pickpocket,"Theft, Pickpocket, >$950",Open or Active,06TH ST \ MISSION ST,24293000.0,Southern,South of Market,6.0,6.0,37.780972,-122.408707,POINT (-122.40870666503906 37.78097152709961),Larceny

In [142]:
# only keep the columns we need
filtered_df = filtered_df[['Incident ID', 'Consolidated Category', 'Latitude', 'Longitude']]
filtered_df.head(3)

    Incident ID Consolidated Category   Latitude   Longitude
1       1448112               Larceny  37.738846 -122.397812
7       1353735               Larceny  37.794643 -122.417520
24      1362304               Larceny  37.780972 -122.408707

In [143]:
import geopandas as gpd
from shapely.geometry import Point

In [144]:
# create GeoDataFrame from your incident coordinates
geometry = [Point(xy) for xy in zip(filtered_df['Longitude'], filtered_df['Latitude'])]
gdf_incidents = gpd.GeoDataFrame(filtered_df, geometry=geometry, crs='EPSG:4326')

In [145]:
# load census tract GeoJSON
census_tracts = gpd.read_file('../../data/basemap.geojson')

In [146]:
# spatial join to get tract info for each incident
df_new = gpd.sjoin(gdf_incidents, census_tracts, 
                                  how='left', predicate='within')

In [147]:
df_new.head(3)

,Incident ID,Consolidated Category,Latitude,Longitude,geometry,index_right,name,tract
1,1448112,Larceny,37.738846,-122.397812,POINT (-122.39781 37.73885),223.0,9809,980900
7,1353735,Larceny,37.794643,-122.417520,POINT (-122.41752 37.79464),13.0,110.01,011001
24,1362304,Larceny,37.780972,-122.408707,POINT (-122.40871 37.78097),161.0,176.02,017602

In [148]:
# only keep columns we need
df_new = df_new[['Consolidated Category', 'name']]

In [149]:
# rename the columns
df_new = df_new.rename(columns={'Consolidated Category': 'Category', 'name': 'Area'})
df_new.head(3)

   Category    Area
1   Larceny    9809
7   Larceny  110.01
24  Larceny  176.02

In [150]:
# reset the index
df_new = df_new.reset_index(drop=True)

In [151]:
# get shape of the final dataframe
print(df_new.shape)

(33698, 2)

In [152]:
# count the number of incidents by category and area
df_count = df_new.groupby(['Area', 'Category']).size().reset_index(name='Count')
df_count.head(3)

     Area  Category  Count
0  101.01   Assault     48
1  101.01  Burglary     29
2  101.01   Larceny    301

In [153]:
# change the columns to area and , and the values to the count of each category
df_pivot = df_count.pivot(index='Area', columns='Category', values='Count').fillna(0).reset_index()
# drop Category
df_pivot = df_pivot.rename_axis(None, axis=1)
# reset index
df_pivot = df_pivot.reset_index(drop=True)
df_pivot.head()

     Area  Assault  Burglary  Larceny  Motor Vehicle Theft  Robbery
0  101.01     48.0      29.0    301.0                 31.0     18.0
1  101.02     23.0       8.0     43.0                  9.0      4.0
2  102.01      6.0       4.0     48.0                 19.0      1.0
3  102.02     17.0      18.0     96.0                 20.0      9.0
4     103     11.0       9.0     79.0                 21.0      2.0

In [154]:
# keep as integers
df_pivot['Assault'] = df_pivot['Assault'].astype(int)
df_pivot['Burglary'] = df_pivot['Burglary'].astype(int)
df_pivot['Larceny'] = df_pivot['Larceny'].astype(int)   
df_pivot['Motor Vehicle Theft'] = df_pivot['Motor Vehicle Theft'].astype(int)
df_pivot['Robbery'] = df_pivot['Robbery'].astype(int)
df_pivot.head()

     Area  Assault  Burglary  Larceny  Motor Vehicle Theft  Robbery
0  101.01       48        29      301                   31       18
1  101.02       23         8       43                    9        4
2  102.01        6         4       48                   19        1
3  102.02       17        18       96                   20        9
4     103       11         9       79                   21        2

In [155]:
# convert numeric columns to proper data types
numeric_columns = ['Assault', 'Burglary', 'Larceny', 'Motor Vehicle Theft', 'Robbery']
df_pivot[numeric_columns] = df_pivot[numeric_columns].apply(pd.to_numeric, errors='coerce')

# create the dictionary in the format you want
result_dict = {
    'assault': df_pivot.set_index('Area')['Assault'].to_dict(),
    'burglary': df_pivot.set_index('Area')['Burglary'].to_dict(),
    'larceny': df_pivot.set_index('Area')['Larceny'].to_dict(),
    'motor vehicle theft': df_pivot.set_index('Area')['Motor Vehicle Theft'].to_dict(),
    'robbery': df_pivot.set_index('Area')['Robbery'].to_dict()
}

# convert to JSON and save to file
import json

with open('./just-crime.json', 'w') as f:
    json.dump(result_dict, f, indent=2)

print("JSON file saved as 'just-crime.json'")

JSON file saved as 'just-crime.json'

In [156]:
import json
import pandas as pd

# load files
with open('just-crime.json', 'r') as f:
    crime_data = json.load(f)
with open('population.json', 'r') as f:
    population_data = json.load(f)

# create final DataFrame
crime_areas = set().union(*[crime_data[ct].keys() for ct in crime_data])
population_areas = set(population_data['value'].keys())
common_areas = crime_areas.intersection(population_areas)

result_data = []
for area in common_areas:
    row = {'Area': area}
    for crime_type in crime_data:
        row[crime_type.title()] = crime_data[crime_type].get(area, 0)
    row['Total Population'] = population_data['value'][area]
    result_data.append(row)

df_final = pd.DataFrame(result_data).sort_values('Area').reset_index(drop=True)

In [157]:
df_final

,Area,Assault,Burglary,Larceny,Motor Vehicle Theft,Robbery,Total Population
0,101.01,48,29,301,31,18,2004
1,101.02,23,8,43,9,4,1795
2,102.01,6,4,48,19,1,2608
3,102.02,17,18,96,20,9,1761
4,103,11,9,79,21,2,3791
...,...,...,...,...,...,...,...
236,9802,0,0,13,0,1,179
237,9803,46,37,178,45,14,49
238,9805.01,15,4,12,19,9,155
239,9806,11,5,19,24,1,1290
240,9809,112,89,251,155,35,322

In [158]:
# convert numeric columns to proper data types
numeric_columns = ['Assault', 'Burglary', 'Larceny', 'Motor Vehicle Theft', 'Robbery', 'Total Population']
df_final[numeric_columns] = df_final[numeric_columns].apply(pd.to_numeric, errors='coerce')

# create the dictionary in the format you want
result_dict = {
    'assault': df_final.set_index('Area')['Assault'].to_dict(),
    'burglary': df_final.set_index('Area')['Burglary'].to_dict(),
    'larceny': df_final.set_index('Area')['Larceny'].to_dict(),
    'motor vehicle theft': df_final.set_index('Area')['Motor Vehicle Theft'].to_dict(),
    'robbery': df_final.set_index('Area')['Robbery'].to_dict(),
    'population': df_final.set_index('Area')['Total Population'].to_dict()
}

# convert to JSON and save to file
import json

with open('../../data/crime.json', 'w') as f:
    json.dump(result_dict, f, indent=2)

print("JSON file saved as 'crime.json'")

JSON file saved as 'crime.json'